### PR TITLE
Widen supported range for ember-modifier to include v4

### PR DESCRIPTION
**Pull request by SergeAstapov**
with https://github.com/ember-modifier/ember-modifier/releases/tag/v4.0.0, we can't bump `ember-modifier` to v4.0.0 in the project due to `peerDependencies` range including only v3

### CODE REVIEW

**Review by chriskrycho — APPROVED** [review]
Good catch; thanks!

**Comment by dfreeman** [comment]
Looking at the test output, there may be some compatibility issues with the v4 `ember-modifier` types?

**Comment by SergeAstapov** [comment]
@dfreeman I’ll look into these, there seem to be tests that needs to be updated.

**Comment by dfreeman** [comment]
I didn't think the types had changed either, but _something_ definitely seems to be going wrong in the tests. 

@SergeAstapov as a starting point you may try merging `main` into your branch—we recently fixed some other CI issues there related to the DT migration.

**Comment by SergeAstapov** [comment]
@dfreeman @chriskrycho *I think* figured out where issue comes from, however can't quite think of the way to fix it.

the `typecheck` was failing in `packages/environment-ember-loose/__tests__/type-tests/modifier.test.ts` file.
first issue was that `NeatModifier` was not converted to latest ember-modifier API. Once this was done, another issue popped up.

the following line causes trouble

```ts
let neat = resolve(NeatModifier);
```

because `resolve` function does not match `Modifier` class signature anymore...
As far as I can understand, `ember-modifier@3.2.7` has `/index.d.ts` file with following contents

```
export { default } from './-private/class/modifier';
export { default as modifier } from './-private/function-based/modifier';
// ...
```

and `./-private/class/modifier` has notable lines

```
// ...
export default interface ClassBasedModifier<S = DefaultSignature> extends Opaque<S> {}
export default class ClassBasedModifier<S = DefaultSignature> {
  // ...
}
// ...
```

*However*, in `ember-modifier@4.0.0` we use `rollup` + `rollup-plugin-ts` for bundling, which results in having `index.d.ts` like so

```ts
// ...
interface ClassBasedModifier<S = DefaultSignature> extends Opaque<S> {}
declare class ClassBasedModifier<S = DefaultSignature> {
  // ...
}
export { ClassBasedModifier as default, modifier };
// ...
```

now I'm little puzzled how to make this back on track...

**Comment by dfreeman** [comment]
Thank you for your work on this @SergeAstapov! I probably won't have a chance to dig in further until after the holidays, but I'm happy to pick it up then and see if we can work out a path forward

**Comment by SergeAstapov** [comment]
sounds like a good plan, thank you @dfreeman!
I'll see if I can find the solution myself. if no updates posted in this thread - consider all my attempts failed.

**Comment by dfreeman** [comment]
Thank you, @SergeAstapov!

**Pull request merged**
